### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by eson57** [balta3/sailfish-gpsinfo#5]
Nice app! Here's a Swedish translation, if you want it.

https://svenskasprakfiler.se/tempfiles/gpsinfo_sv.ts

**Comment by balta3** [comment]
Sure, thanks.
But it would be easier if you create a pull request, this way you would count as contributor in github. But if you do not care I will take your ts file.

**Comment by eson57** [comment]
Actually I don't really know how to do that, but it seem like a lot of work for a simple translation file, so please take the file if you wish.
