### ISSUE TITLE
Russian translation suggestion

### ISSUE THREAD

**Issue by a-kalmykov** [balta3/sailfish-gpsinfo#8]
Hello!
I would like to suggest a russian translation for GPSInfo. I have made a .ts file, so how I can contribute it?

**Comment by balta3** [comment]
Hello, sorry for the late response. I've created a Transifex-Project for translations, do you have an account there? You can simply send me the ts file or create a pull-request here if you want.

https://www.transifex.com/organization/harbour-gpsinfo/dashboard

**Comment by a-kalmykov** [comment]
Hello!
Yes, I have a Transifex account and I made request for Russian translation there. Please create Russian language group and I will join after that. Thanks :-)

чт июня 18 21:04:43 2015 GMT+0300 получено от balta3:
